export const BOARD_SIZE = 500;

export const levels = [
  {
    id: 1,
    answer: '中',
    title: '标准探针',
    subtitle: '中',
    rule: '拖动红色 A 点和蓝色 B 点，观察两点连线穿过隐藏汉字的填充量。',
    mode: 'free',
    rules: [
      '拖动探针：用鼠标拖动红色 A 点和蓝色 B 点，也可以用 WASD 精细移动 A 点。',
      '观察长度：连接线上显示“标准长度 / 命中量百分比”。',
      '记录扫描：最多记录 3 条历史扫描线。',
      '提交答案：本 Demo 不限制提交次数。',
    ],
    initialA: { x: 90, y: 130 },
    initialB: { x: 410, y: 370 },
  },
  {
    id: 2,
    answer: '艾',
    title: '标准探针',
    subtitle: '艾',
    rule: '规则不变，但字形出现斜向和交叉笔画，需要从更多角度探测。',
    mode: 'free',
    rules: [
      '拖动探针：用鼠标拖动红色 A 点和蓝色 B 点，也可以用 WASD 精细移动 A 点。',
      '观察长度：连接线上显示“标准长度 / 命中量百分比”。',
      '记录扫描：最多记录 3 条历史扫描线。',
      '提交答案：本 Demo 不限制提交次数。',
    ],
    initialA: { x: 80, y: 380 },
    initialB: { x: 420, y: 120 },
  },
  {
    id: 3,
    answer: '浅',
    title: '标准探针',
    subtitle: '浅',
    rule: '规则不变，目标字更复杂。用多条线判断左右结构和密集笔画。',
    mode: 'free',
    rules: [
      '拖动探针：用鼠标拖动红色 A 点和蓝色 B 点，也可以用 WASD 精细移动 A 点。',
      '观察长度：连接线上显示“标准长度 / 命中量百分比”。',
      '记录扫描：最多记录 3 条历史扫描线。',
      '提交答案：本 Demo 不限制提交次数。',
    ],
    initialA: { x: 70, y: 250 },
    initialB: { x: 430, y: 250 },
  },
  {
    id: 4,
    answer: '红',
    title: '水平探针',
    subtitle: '红',
    rule: '附加规则：A/B 连线必须保持水平，只能通过横向切片摸出字形。',
    mode: 'horizontal',
    rules: [
      '附加规则：A/B 连线必须保持水平，只能通过横向切片摸出字形。',
      '观察长度：连接线上显示“标准长度 / 命中量百分比”。',
      '记录扫描：最多记录 3 条历史扫描线。',
    ],
    initialA: { x: 80, y: 250 },
    initialB: { x: 420, y: 250 },
  },
  {
    id: 5,
    answer: '只',
    title: '双锚探针',
    subtitle: '只',
    rule: '附加规则：左上和右下各有一个固定基点，A/B 探针分别从两个基点拉出进行探测。',
    mode: 'dualAnchor',
    metricMode: 'length',
    rules: [
      '附加规则：左上和右下各有一个固定基点，A/B 探针分别从两个基点拉出进行探测。',
      '本关显示每段“检测长度 / 命中黑色长度”，不显示百分比。',
      '记录扫描：最多记录 3 条历史扫描线。',
    ],
    anchorA: 'topLeft',
    anchorB: 'bottomRight',
    initialA: { x: 130, y: 130 },
    initialB: { x: 370, y: 370 },
  },
  {
    id: 6,
    answer: '羽',
    title: '点触声呐',
    subtitle: '羽',
    rule: '附加规则：本关不显示命中数值，请按住鼠标拖动，用声音高低判断是否摸到笔画。',
    mode: 'sonarPoint',
    rules: [
      '附加规则：本关只依靠声音判断，不显示命中数值。',
      '按住鼠标在网格中拖动；低音代表空白，高音代表摸到笔画。',
      '建议先打开设备音量，再开始探测。',
    ],
    initialA: { x: 250, y: 250 },
    initialB: { x: 250, y: 250 },
  },
  {
    id: 7,
    answer: '门',
    title: '镭射手枪',
    subtitle: '门',
    rule: '附加规则：枪口只能沿边框移动，拖动准星选择方向，点击发射镭射。',
    mode: 'laserGun',
    shotLimit: 20,
    rules: [
      '附加规则：枪口可以沿画布边框移动。',
      '拖动蓝色准星选择射击方向，点击“发射”发射一枚镭射。',
      '镭射穿过笔画会留下更亮的绿色轨迹，最多 20 发。',
    ],
    initialA: { x: 0, y: 250 },
    initialB: { x: 360, y: 250 },
  },
  {
    id: 8,
    answer: '回',
    title: '旋转雷达',
    subtitle: '回',
    rule: '附加规则：拖动雷达中心，调节半径和转速，雷达命中率超过 98 时变红。',
    mode: 'radar',
    radius: 160,
    speed: 0.55,
    rules: [
      '附加规则：拖动雷达中心进行自动旋转扫描。',
      '半径范围 37.5 到 300；转速最快 1 秒一圈，最慢 20 秒一圈。',
      '雷达线命中率达到 98 以上时会变红。',
    ],
    initialA: { x: 250, y: 250 },
    initialB: { x: 410, y: 250 },
  },
  {
    id: 9,
    answer: '王',
    title: '圆形声波',
    subtitle: '王',
    rule: '附加规则：点击产生由 12 条射线组成的圆形声波；射线碰到隐藏笔画后停止，并激发亮色小涟漪。',
    mode: 'radialWave',
    cooldownMs: 1000,
    rayCount: 12,
    rules: [
      '附加规则：点击任意位置产生一圈由 12 条射线组成的圆形声波。',
      '每条射线向外扩散，碰到隐藏笔画时停止。',
      '命中点会激发颜色更亮的小涟漪，帮助判断笔画边界。',
      '每秒最多触发一次声波。',
    ],
    initialA: { x: 250, y: 250 },
    initialB: { x: 250, y: 250 },
  },
  {
    id: 10,
    answer: '大象',
    title: 'DLC 剪影',
    subtitle: '🐘',
    rule: 'Surprise：本关目标不是汉字。点击产生水波，通过轮廓判断隐藏对象。',
    mode: 'ripple',
    targetType: 'elephant',
    cooldownMs: 120,
    revealTtlMs: 1000,
    note: '说明：受浏览器实时渲染性能限制，这一关没有做成最完整的剪影显影效果。建议在画布不同位置多点几次，观察短暂出现的轮廓点，就能逐步看出隐藏对象。',
    rules: [
      'Surprise：本关目标不是汉字，而是一个隐藏剪影。',
      '点击产生水波，通过耳朵、鼻子、腿部轮廓判断它是什么。',
      '显影点会在 1 秒后消失，需要快速观察轮廓。',
    ],
    initialA: { x: 250, y: 250 },
    initialB: { x: 250, y: 250 },
  },
];
